# Make sure to check the documentation at https://goreleaser.com
version: 2
release:
  draft: true
  replace_existing_draft: true

before:
  hooks:
    # You may remove this if you don't use go modules.
    - sh -c 'cd ./cmd/tkey-runapp && go mod tidy'
    # you may remove this if you don't need go generate
    - sh -c 'cd ./cmd/tkey-runapp && go generate ./...'
builds:
  - id: linux
    dir: ./cmd/tkey-runapp
    binary: tkey-runapp
    env:
      - GOPROXY=https://proxy.golang.org,direct
      - GOSUMDB=sum.golang.org
      - CGO_ENABLED=0

    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false

    # Custom ldflags mostly to avoid setting main.date which for some
    # reason is default
    ldflags:
      -w -X main.version={{ .Version }} -buildid=

  - id: darwin
    dir: ./cmd/tkey-runapp
    binary: tkey-runapp
    env:
      - GOPROXY=https://proxy.golang.org,direct
      - GOSUMDB=sum.golang.org
      - CGO_ENABLED=1

    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false

    # Custom ldflags mostly to avoid setting main.date which for some
    # reason is default
    ldflags:
      -w -X main.version={{ .Version }} -buildid=

  - id: windows
    dir: ./cmd/tkey-runapp
    binary: tkey-runapp
    env:
      - GOPROXY=https://proxy.golang.org,direct
      - GOSUMDB=sum.golang.org
      - CGO_ENABLED=0

    goos:
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false

    # Custom ldflags mostly to avoid setting main.date which for some
    # reason is default
    ldflags:
      -w -X main.version={{ .Version }} -buildid=

universal_binaries:
  -
    ids:
      - darwin
    replace: true
    name_template: "tkey-runapp"
    hooks:
      post: gon gon.hcl

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ "tkey-runapp" }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "all" }}universal
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
    files:
   #   - src: doc/tkey-sign.1
   #     dst: man
   #     strip_parent: true

nfpms:
  # note that this is an array of nfpm configs
  - #
    # ID of the nfpm config, must be unique.
    #
    # Default: 'default'
    #id: foo

    # Name of the package.
    # Default: ProjectName
    # Templates: allowed. (since v1.18)
    package_name: tkey-runapp

    # Your app's vendor.
    vendor: Tillitis AB

    # Your app's homepage.
    homepage: https://tillitis.se/

    # Your app's maintainer (probably you).
    maintainer: Tillitis <hello@tillitis.se>

    # Your app's description.
    description: |-
      TKey-runapp
      A tool to load an application binary onto the
      Tillitis TKey and start it.

    # Your app's license.
    license: GPL 2.0

    # Formats to be generated.
    formats:
      - apk
      - deb
      - rpm
      - archlinux # Since: v1.13

    # Contents to add to the package.
    # GoReleaser will automatically add the binaries.
    contents:
    #  - src: doc/tkey-sign.1
    #    dst: /usr/share/man/man1/tkey-sign.1

    # Custom configuration applied only to the Deb packager.
    deb:
      # Lintian overrides
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort:
  filters:
    exclude:
      - '^docs:'
      - '^test:'


# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

#  LocalWords:  sign
