
name: ci

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  # allow manual runs:
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tillitis/tkey-builder:4
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0
          persist-credentials: false

      - name: fix
        # https://github.com/actions/runner-images/issues/6775
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: check for SPDX tags
        run: ./tools/spdx-ensure

      # Ubuntu has stopped publishing packages we use in
      # tkey-builder:4 so we can't do this right now. Kept for a later
      # update.
      # - name: Install missing headers to be able to build hidread
      #   run: apt-get update && apt-get -y install libusb-dev libudev-dev

      - name: make
        run: make -j

  reuse-compliance-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v4
      with:
        args: lint
